routes:

collections:
  /:
    permalink: /{slug}/
    template: index
  /talks/:
    permalink: /talks/{slug}/
    template: talk
    filter: primary_tag:talk

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
